### ISSUE TITLE
Missing installation instructions

### ISSUE THREAD

**Issue by DDvO** [polhenarejos/acme_email#14]
I tried the following, by best guess:
```
python3 -m pip install zope certbot cryptography pkcs7
sudo python3 ./setup.py build install
```
but still `cli.py` returns
```
An unexpected error occurred:
ImportError: cannot import name 'pkcs7' from 'cryptography.hazmat.primitives.serialization' (/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/serialization/__init__.py)
```

**Comment by LecrisUT** [comment]
Preferably the instructions will be based on `python -m venv` so you don't need to sudo. In your case probably an openssl package was missing for the distro? Maybe adding instructions via `homebrew` for mac and [packagekit](https://www.freedesktop.org/software/PackageKit/pk-using.html) will be helpful.

**Comment by polhenarejos** [comment]
You should use virtualenv and install with
`pip3 install .`

**Comment by DDvO** [comment]
I see - this works :)
Good that you added installation instructions to`README.md`.
