### ISSUE TITLE
State clearly and upfront that a specific root cert must be trusted

### ISSUE THREAD

**Issue by DDvO** [polhenarejos/acme_email#18]
I have not been able to get a certificate yet due to technical trouble,
but as far as I understand the service meanwhile, 
the certs produced are not verifiable using a vanilla trust store (by Thunderbird, Windows, Android, etc.), right?

**Comment by polhenarejos** [comment]
Probably true. We employ our CA. So, in order to use our deployed certificates, the CA shall be trusted.

**Comment by DDvO** [comment]
Please state upfront on https://acme.castle.cloud/documentation/chain-of-trust/
that your solution requires adding a non-standard trust anchor.
