### ISSUE TITLE
Missing CP / CPS

### ISSUE THREAD

**Issue by fpedrei** [polhenarejos/acme_email#19]
As stated in the terms of service:

> 4.4 IMPORTANT DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY
> 
> EXCEPT AS EXPRESSLY SET FORTH IN CTTC’S CERTIFICATE POLICY AND CERTIFICATE PRACTICE STATEMENT [...]

Where can these CTTC CP and CPS be found?

**Comment by polhenarejos** [comment]
All legal documents can be found at https://acme.castle.cloud/legal/

Legal docs are added into Documentation section.
