### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by majonez** [polhenarejos/acme_email#3]
Hi,

I receive internal server error, when trying to make a cert with the interactive authenticator:

2021-07-19 04:27:55,540:DEBUG:urllib3.connectionpool:https://acme.castle.cloud:443 &quot;POST /acme/order/XXXXXXXX/finalize HTTP/1.1&quot; 500 None
2021-07-19 04:27:55,540:DEBUG:acme.client:Received response:
HTTP 500
Date: Mon, 19 Jul 2021 02:27:55 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
X-Frame-Options: DENY
Vary: Cookie
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
CF-Cache-Status: DYNAMIC
Expect-CT: max-age=604800, report-uri=&quot;https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct&quot;
Report-To: {&quot;endpoints&quot;:[{&quot;url&quot;:&quot;https:\/\/a.nel.cloudflare.com\/report\/v3?s=5vVWO5XU%2BFFP7Pt5xHSHnPTFD0DO70p63YVjufQCSpxy0GG7Pz7%2BzCV5zb73cFfMZYAIefLaLSpZ8yiaEh4N3fKghp8QgE7ShEejSIjJ2s2hsrYbX3BcGXoLF6glP11Q365wOQ%3D%3D&quot;}],&quot;group&quot;:&quot;cf-nel&quot;,&quot;max_age&quot;:604800}
NEL: {&quot;report_to&quot;:&quot;cf-nel&quot;,&quot;max_age&quot;:604800}
Server: cloudflare
CF-RAY: 6710836df9a0bc54-LHR
alt-svc: h3-27=&quot;:443&quot;; ma=86400, h3-28=&quot;:443&quot;; ma=86400, h3-29=&quot;:443&quot;; ma=86400, h3=&quot;:443&quot;; ma=86400

&lt;!doctype html&gt;
&lt;html lang=&quot;en&quot;&gt;
&lt;head&gt;
&lt;title&gt;Server Error (500)&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;h1&gt;Server Error (500)&lt;/h1&gt;&lt;p&gt;&lt;/p&gt;
&lt;/body&gt;
&lt;/html&gt;

2021-07-19 04:27:55,541:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File &quot;/Users/andrew/acme_email/cli.py&quot;, line 164, in &lt;module&gt;
    main(args)
  File &quot;/Users/andrew/acme_email/cli.py&quot;, line 117, in main
    request_cert(args, config)
  File &quot;/Users/andrew/acme_email/cli.py&quot;, line 89, in request_cert
    cert_path, chain_path, fullchain_path = certbot_main._csr_get_and_save_cert(config, le_client)
  File &quot;/usr/local/lib/python3.9/site-packages/certbot-1.17.0-py3.9.egg/certbot/_internal/main.py&quot;, line 1354, in _csr_get_and_save_cert
    cert, chain = le_client.obtain_certificate_from_csr(csr)
  File &quot;/usr/local/lib/python3.9/site-packages/certbot-1.17.0-py3.9.egg/certbot/_internal/client.py&quot;, line 290, in obtain_certificate_from_csr
    orderr = self.acme.finalize_order(orderr, deadline,
  File &quot;/usr/local/lib/python3.9/site-packages/acme-1.17.0-py3.9.egg/acme/client.py&quot;, line 923, in finalize_order
    return cast(ClientV2, self.client).finalize_order(
  File &quot;/usr/local/lib/python3.9/site-packages/acme-1.17.0-py3.9.egg/acme/client.py&quot;, line 745, in finalize_order
    self._post(orderr.body.finalize, wrapped_csr)
  File &quot;/usr/local/lib/python3.9/site-packages/acme-1.17.0-py3.9.egg/acme/client.py&quot;, line 86, in _post
    return self.net.post(*args, **kwargs)
  File &quot;/usr/local/lib/python3.9/site-packages/acme-1.17.0-py3.9.egg/acme/client.py&quot;, line 1201, in post
    return self._post_once(*args, **kwargs)
  File &quot;/usr/local/lib/python3.9/site-packages/acme-1.17.0-py3.9.egg/acme/client.py&quot;, line 1214, in _post_once
    response = self._check_response(response, content_type=content_type)
  File &quot;/usr/local/lib/python3.9/site-packages/acme-1.17.0-py3.9.egg/acme/client.py&quot;, line 1077, in _check_response
    raise errors.ClientError(response)
acme.errors.ClientError: &lt;Response [500]&gt;
2021-07-19 04:27:55,547:ERROR:certbot._internal.log:An unexpected error occurred:
2021-07-19 04:27:55,547:ERROR:certbot._internal.log:acme.errors.ClientError: &lt;Response [500]&gt;

**Comment by polhenarejos** [comment]
Seems fixed in the backend. 
Reopen if it happens again.

**Comment by majonez** [comment]
Retried today. Same issue:

2021-08-14 12:26:03,061:DEBUG:urllib3.connectionpool:https://acme.castle.cloud:443 &quot;POST /acme/order/zzf6H4t0o9c/finalize HTTP/1.1&quot; 500 None
2021-08-14 12:26:03,062:DEBUG:acme.client:Received response:
HTTP 500
Date: Sat, 14 Aug 2021 10:26:03 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
x-frame-options: DENY
vary: Cookie
x-content-type-options: nosniff
referrer-policy: same-origin
CF-Cache-Status: DYNAMIC
Expect-CT: max-age=604800, report-uri=&quot;https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct&quot;
Report-To: {&quot;endpoints&quot;:[{&quot;url&quot;:&quot;https:\/\/a.nel.cloudflare.com\/report\/v3?s=j5lZkuVzCfz%2F2N6ogjnhLLYsHnUHfEszWszReSD48EVB8Aafiyccm3cw%2FRYz0rIBAbZYH5oT3TRaiqvLl5bP4THCcrSWP0hr5BZBbuepPfXECmvPSyOqoXEtZAJQ%2By0Joeubsw%3D%3D&quot;}],&quot;group&quot;:&quot;cf-nel&quot;,&quot;max_age&quot;:604800}
NEL: {&quot;success_fraction&quot;:0,&quot;report_to&quot;:&quot;cf-nel&quot;,&quot;max_age&quot;:604800}
Server: cloudflare
CF-RAY: 67e97b904d644e0e-FRA
alt-svc: h3-27=&quot;:443&quot;; ma=86400, h3-28=&quot;:443&quot;; ma=86400, h3-29=&quot;:443&quot;; ma=86400, h3=&quot;:443&quot;; ma=86400


&lt;!doctype html&gt;
&lt;html lang=&quot;en&quot;&gt;
&lt;head&gt;
&lt;title&gt;Server Error (500)&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;h1&gt;Server Error (500)&lt;/h1&gt;&lt;p&gt;&lt;/p&gt;
&lt;/body&gt;
&lt;/html&gt;

2021-08-14 12:26:03,062:DEBUG:certbot._internal.log:Exiting abnormally:
Traceback (most recent call last):
  File &quot;/Users/andrew/acme_email/cli.py&quot;, line 164, in &lt;module&gt;
    main(args)
  File &quot;/Users/andrew/acme_email/cli.py&quot;, line 117, in main
    request_cert(args, config)
  File &quot;/Users/andrew/acme_email/cli.py&quot;, line 89, in request_cert
    cert_path, chain_path, fullchain_path = certbot_main._csr_get_and_save_cert(config, le_client)
  File &quot;/usr/local/lib/python3.9/site-packages/certbot/_internal/main.py&quot;, line 1354, in _csr_get_and_save_cert
    cert, chain = le_client.obtain_certificate_from_csr(csr)
  File &quot;/usr/local/lib/python3.9/site-packages/certbot/_internal/client.py&quot;, line 290, in obtain_certificate_from_csr
    orderr = self.acme.finalize_order(orderr, deadline,
  File &quot;/usr/local/lib/python3.9/site-packages/acme/client.py&quot;, line 934, in finalize_order
    return cast(ClientV2, self.client).finalize_order(
  File &quot;/usr/local/lib/python3.9/site-packages/acme/client.py&quot;, line 751, in finalize_order
    self._post(orderr.body.finalize, wrapped_csr)
  File &quot;/usr/local/lib/python3.9/site-packages/acme/client.py&quot;, line 87, in _post
    return self.net.post(*args, **kwargs)
  File &quot;/usr/local/lib/python3.9/site-packages/acme/client.py&quot;, line 1212, in post
    return self._post_once(*args, **kwargs)
  File &quot;/usr/local/lib/python3.9/site-packages/acme/client.py&quot;, line 1225, in _post_once
    response = self._check_response(response, content_type=content_type)
  File &quot;/usr/local/lib/python3.9/site-packages/acme/client.py&quot;, line 1088, in _check_response
    raise errors.ClientError(response)
acme.errors.ClientError: &lt;Response [500]&gt;
2021-08-14 12:26:03,064:ERROR:certbot._internal.log:An unexpected error occurred:
2021-08-14 12:26:03,064:ERROR:certbot._internal.log:acme.errors.ClientError: &lt;Response [500]&gt;
